### ISSUE TITLE
Error: pandoc document conversion failed with error 83

### ISSUE THREAD

**Issue by acircleda** [atusy/ftExtra#36] opened 2020-12-17 13:18 UTC
Getting this error:

```
Error running filter C:/Users/aschmidt/Documents/R/win-library/4.0/ftExtra/lua/math.lua:
[string "C:/Users/aschmidt/Documents/R/win-library/4.0..."]:18: attempt to index a nil value (field 'system')
stack traceback:
	[string "C:/Users/aschmidt/Documents/R/win-library/4.0..."]:18: in main chunk
Error: pandoc document conversion failed with error 83
```
This occurs in both R markdown and R script, even when just running in-console.

Code:

```
library(tidyverse)
library(flextable)
library(ftExtra)

tribble(~Abbreviation, ~Definition,
        "CO~2~", "carbon dioxide",
        "CO~2~e", "carbon dioxide equivalent") %>%
  flextable() %>%
  ftExtra::colformat_md()
```

Session Info:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
 [1] ftExtra_0.1.0    flextable_0.5.10 forcats_0.5.0   
 [4] stringr_1.4.0    dplyr_1.0.2      purrr_0.3.4     
 [7] readr_1.3.1      tidyr_1.1.2      tibble_3.0.3    
[10] ggplot2_3.3.1    tidyverse_1.3.0 

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.0  xfun_0.19         haven_2.3.1      
 [4] colorspace_1.4-1  vctrs_0.3.4       generics_0.0.2   
 [7] htmltools_0.5.0   base64enc_0.1-3   yaml_2.2.1       
[10] blob_1.2.1        rlang_0.4.7       pillar_1.4.6     
[13] glue_1.4.2        withr_2.2.0       DBI_1.1.0        
[16] gdtools_0.2.2     dbplyr_1.4.4      uuid_0.1-4       
[19] modelr_0.1.8      readxl_1.3.1      lifecycle_0.2.0  
[22] munsell_0.5.0     gtable_0.3.0      cellranger_1.1.0 
[25] zip_2.1.1         rvest_0.3.5       evaluate_0.14    
[28] knitr_1.30        fansi_0.4.1       broom_0.7.0      
[31] Rcpp_1.0.5        scales_1.1.1      backports_1.1.9  
[34] jsonlite_1.7.1    systemfonts_0.2.2 fs_1.4.1         
[37] hms_0.5.3         digest_0.6.25     stringi_1.5.3    
[40] bookdown_0.21     grid_4.0.2        cli_2.0.2        
[43] tools_4.0.2       magrittr_1.5      crayon_1.3.4     
[46] pkgconfig_2.0.3   ellipsis_0.3.1    data.table_1.12.8
[49] xml2_1.3.2        reprex_0.3.0      lubridate_1.7.8  
[52] officer_0.3.15    assertthat_0.2.1  rmarkdown_2.5    
[55] httr_1.4.2        rstudioapi_0.11   R6_2.4.1         
[58] compiler_4.0.2
```

**Comment by atusy** [comment] 2020-12-17 13:21
Thank you for using ftExtra.

This is a duplicate of https://github.com/atusy/ftExtra/issues/34, which is already solved.
Please use development version of ftExtra by `remotes::install_github("atusy/ftExtra")`.

**Comment by acircleda** [comment] 2020-12-17 13:39
Thanks. I installed the dev version and updated all my dependencies. Get this error instead:

```
option `--lua-filter' requires an argument SCRIPTPATH
Try pandoc.exe --help for more information.
Error: pandoc document conversion failed with error 2`
``

**Comment by atusy** [comment] 2020-12-17 13:42
@acircleda Thanks. I'll try to fix.

**Comment by atusy** [comment] 2020-12-17 13:57
@acircleda Would you try `remotes::install_github("atusy/ftExtra#37")`?

**Comment by acircleda** [comment] 2020-12-17 14:00
Success!
![image](https://user-images.githubusercontent.com/51770624/102497117-438af280-4046-11eb-9336-2842a52be753.png)

**Comment by atusy** [comment] 2020-12-17 14:06
Great!! I'll merge the PR. Thanks for your cooperation!

**Closed** 2020-12-17 14:11 UTC
